import os  # Provides access to operating-system environment variables.
import sqlite3  # Provides SQLite database access for the original local database.

import psycopg  # Provides PostgreSQL database access.
from psycopg import sql  # Provides safe SQL construction for table and column identifiers.


# ---------------------------------------------------------------------------
# DATABASE SETTINGS
# ---------------------------------------------------------------------------

SQLITE_DB = os.getenv("SQLITE_DB", "hardware_inventory.db")
# Uses the existing SQLite database in the project folder unless SQLITE_DB is set.

DATABASE_URL = os.getenv("DATABASE_URL")
# Reads the PostgreSQL connection string from the environment.


if not DATABASE_URL:
    # Stops the migration when the PostgreSQL connection string is missing.
    raise RuntimeError(
        "DATABASE_URL is not set. Set DATABASE_URL to your PostgreSQL/Supabase connection string."
    )


# ---------------------------------------------------------------------------
# CONNECT TO BOTH DATABASES
# ---------------------------------------------------------------------------

sqlite_conn = sqlite3.connect(SQLITE_DB)
# Opens the original SQLite database.

sqlite_conn.row_factory = sqlite3.Row
# Allows SQLite rows to be accessed using column names.

pg_conn = psycopg.connect(DATABASE_URL)
# Opens the destination PostgreSQL database.

pg_conn.autocommit = False
# Uses one transaction so the migration can be rolled back if anything fails.


# ---------------------------------------------------------------------------
# TABLE DEFINITIONS
# These definitions match the current app.py SQLite schema.
# ---------------------------------------------------------------------------

table_definitions = {
    "users": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "username TEXT UNIQUE NOT NULL",
        "email TEXT UNIQUE NOT NULL",
        "password_hash TEXT NOT NULL",
        "role TEXT NOT NULL DEFAULT 'user'",
        "failed_attempts INTEGER NOT NULL DEFAULT 0",
    ],

    "password_resets": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "username TEXT NOT NULL",
        "email TEXT NOT NULL",
        "new_password TEXT NOT NULL",
        "status TEXT NOT NULL DEFAULT 'Pending'",
        "created_at TEXT NOT NULL DEFAULT ''",
    ],

    "hardware": [
        "item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "item_name TEXT NOT NULL",
        "category TEXT NOT NULL",
        "quantity INTEGER NOT NULL DEFAULT 0",
        "unit_price DOUBLE PRECISION NOT NULL DEFAULT 0",
        "status TEXT NOT NULL DEFAULT 'Out of Stock'",
    ],

    "hardware_requests": [
        "request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "username TEXT NOT NULL",
        "name TEXT NOT NULL",
        "student_id TEXT NOT NULL",
        "professor TEXT NOT NULL",
        "subject TEXT NOT NULL",
        "schedule TEXT NOT NULL",
        "hardware_item TEXT NOT NULL",
        "category TEXT NOT NULL DEFAULT 'Others'",
        "quantity INTEGER NOT NULL DEFAULT 1",
        "queue_number INTEGER NOT NULL",
        "approval_status TEXT NOT NULL DEFAULT 'Pending'",
        "approval_code TEXT NOT NULL DEFAULT ''",
        "borrow_status TEXT NOT NULL DEFAULT 'Not Borrowed'",
        "return_status TEXT NOT NULL DEFAULT ''",
        "time_checkin TEXT NOT NULL DEFAULT ''",
        "time_checkout TEXT NOT NULL DEFAULT ''",
        "created_at TEXT NOT NULL DEFAULT ''",
    ],

    "audit_log": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "username TEXT NOT NULL",
        "action TEXT NOT NULL",
        "item_name TEXT",
        "quantity INTEGER",
        "request_id BIGINT",
        "details TEXT",
        "created_at TEXT NOT NULL",
    ],
}


# ---------------------------------------------------------------------------
# ID COLUMNS
# Used later to synchronize PostgreSQL identity sequences.
# ---------------------------------------------------------------------------

identity_columns = {
    "users": "id",
    "password_resets": "id",
    "hardware": "item_id",
    "hardware_requests": "request_id",
    "audit_log": "id",
}


# ---------------------------------------------------------------------------
# COLUMN COMPATIBILITY
# The current app.py uses these exact names. The migration also supports
# a few older versions of the project where columns may have been absent.
# ---------------------------------------------------------------------------

default_values = {
    "password_resets": {
        "created_at": "",
    },
    "hardware_requests": {
        "category": "Others",
        "approval_code": "",
        "borrow_status": "Not Borrowed",
        "return_status": "",
        "time_checkin": "",
        "time_checkout": "",
        "created_at": "",
    },
    "hardware": {
        "quantity": 0,
        "unit_price": 0.0,
        "status": "Out of Stock",
    },
}


def sqlite_table_exists(conn, table_name):
    """Returns True when the source SQLite table exists."""
    row = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name=?",
        (table_name,),
    ).fetchone()
    return row is not None


def sqlite_columns(conn, table_name):
    """Returns the source SQLite columns for a table."""
    return [
        row[1]
        for row in conn.execute(f"PRAGMA table_info({table_name})").fetchall()
    ]


def get_source_value(row, source_columns, table_name, column_name):
    """
    Gets a source value by column name.

    If an older SQLite database does not contain a newer column, a safe
    application-compatible default is returned.
    """
    if column_name in source_columns:
        return row[column_name]

    return default_values.get(table_name, {}).get(column_name)


def create_tables(pg_cur):
    """Creates all PostgreSQL tables required by the current Flask app."""
    for table_name, columns in table_definitions.items():
        column_sql = sql.SQL(", ").join(
            sql.SQL(column_definition)
            for column_definition in columns
        )

        create_sql = sql.SQL(
            "CREATE TABLE IF NOT EXISTS {} ({})"
        ).format(
            sql.Identifier(table_name),
            column_sql,
        )

        pg_cur.execute(create_sql)


def check_destination_is_empty(pg_cur):
    """
    Prevents accidental duplicate migration.

    The migration is intended to be run against a new/empty PostgreSQL
    database. If any application table already contains rows, stop.
    """
    for table_name in table_definitions:
        count_sql = sql.SQL(
            "SELECT COUNT(*) FROM {}"
        ).format(
            sql.Identifier(table_name)
        )

        pg_cur.execute(count_sql)
        count = pg_cur.fetchone()[0]

        if count > 0:
            raise RuntimeError(
                f"Destination table '{table_name}' is not empty "
                f"({count} row(s)). Migration stopped to prevent duplicates."
            )


def migrate_table(pg_cur, sqlite_cur, table_name):
    """Copies one SQLite table into its PostgreSQL equivalent."""

    source_columns = sqlite_columns(sqlite_conn, table_name)

    if not source_columns:
        return 0

    sqlite_cur.execute(
        f"SELECT * FROM {table_name}"
    )

    rows = sqlite_cur.fetchall()

    if not rows:
        return 0

    # Only migrate columns that exist in the PostgreSQL definition.
    destination_columns = [
        definition.split()[0]
        for definition in table_definitions[table_name]
    ]

    # Preserve the order used by the source table where possible.
    insert_columns = [
        column
        for column in source_columns
        if column in destination_columns
    ]

    # Add missing application columns using safe defaults.
    for column in destination_columns:
        if column not in insert_columns and column in default_values.get(
            table_name, {}
        ):
            insert_columns.append(column)

    if not insert_columns:
        raise RuntimeError(
            f"No compatible columns found for source table '{table_name}'."
        )

    column_identifiers = sql.SQL(", ").join(
        sql.Identifier(column)
        for column in insert_columns
    )

    placeholders = sql.SQL(", ").join(
        sql.Placeholder()
        for _ in insert_columns
    )

    insert_sql = sql.SQL(
        "INSERT INTO {} ({}) VALUES ({})"
    ).format(
        sql.Identifier(table_name),
        column_identifiers,
        placeholders,
    )

    for row in rows:
        values = []

        for column in insert_columns:
            value = get_source_value(
                row,
                source_columns,
                table_name,
                column,
            )

            # PostgreSQL NOT NULL columns should not receive None when
            # the application has a sensible default.
            if value is None and column in default_values.get(table_name, {}):
                value = default_values[table_name][column]

            values.append(value)

        pg_cur.execute(insert_sql, values)

    return len(rows)


def reset_identity_sequences(pg_cur):
    """
    Synchronizes PostgreSQL identity sequences with the migrated IDs.

    This is important because the migration explicitly copies the original
    SQLite IDs. The next INSERT must therefore continue after the highest
    migrated ID.
    """
    for table_name, id_column in identity_columns.items():

        sequence_sql = sql.SQL(
            """
            SELECT setval(
                pg_get_serial_sequence(%s, %s),
                COALESCE(MAX({id_column}), 1),
                MAX({id_column}) IS NOT NULL
            )
            FROM {table_name}
            """
        ).format(
            id_column=sql.Identifier(id_column),
            table_name=sql.Identifier(table_name),
        )

        pg_cur.execute(
            sequence_sql,
            (table_name, id_column),
        )


def main():
    counts = {}

    try:
        pg_cur = pg_conn.cursor()
        sqlite_cur = sqlite_conn.cursor()

        print("Creating PostgreSQL tables...")
        create_tables(pg_cur)

        print("Checking whether the PostgreSQL tables are empty...")
        check_destination_is_empty(pg_cur)

        print("Starting migration...")

        for table_name in table_definitions:

            if not sqlite_table_exists(sqlite_conn, table_name):
                print(
                    f"WARNING: SQLite table '{table_name}' does not exist. "
                    "Skipping."
                )
                counts[table_name] = 0
                continue

            print(f"Migrating table: {table_name}")

            counts[table_name] = migrate_table(
                pg_cur,
                sqlite_cur,
                table_name,
            )

        print("Synchronizing PostgreSQL identity sequences...")
        reset_identity_sequences(pg_cur)

        pg_conn.commit()

        print()
        print("==========================================")
        print("MIGRATION COMPLETED SUCCESSFULLY")
        print("==========================================")
        print(f"users:             {counts['users']}")
        print(f"password_resets:   {counts['password_resets']}")
        print(f"hardware:          {counts['hardware']}")
        print(f"hardware_requests: {counts['hardware_requests']}")
        print(f"audit_log:         {counts['audit_log']}")
        print("==========================================")

    except Exception as exc:
        pg_conn.rollback()

        print()
        print("==========================================")
        print("MIGRATION FAILED")
        print("==========================================")
        print(f"Reason: {exc}")
        print("All PostgreSQL changes were rolled back.")
        print("==========================================")

        raise

    finally:
        sqlite_conn.close()
        pg_conn.close()


if __name__ == "__main__":
    main()
